fix: bsc rate limit for alm
fuseio/tokenbridge pull request #10
Opened 2021-11-07 20:48 UTC by t0mcr8se

2021-11-08 09:47 UTC, leonprou requested changes

2021-11-08 09:47 UTC, leonprou commented on alm/.env.example
> +COMMON_FOREIGN_RPC_URL=https://red-restless-morning.bsc.quiknode.pro/<quicknode-project-id>/
please delete the quicksart  RPC.

2021-11-08 09:47 UTC, leonprou commented on alm/.env.example
> +COMMON_FOREIGN_RPC_URL=https://red-restless-morning.bsc.quiknode.pro/<quicknode-project-id>/
if there any requirements to the RPC, let's mention them in a comment

2021-11-08 09:47 UTC, leonprou commented on alm/Dockerfile
> +RUN NOYARNPOSTINSTALL=1 yarn install --frozen-lockfile
you know why they deleted the --`production` flag?

2021-11-08 12:03 UTC, t0mcr8se commented on alm/.env.example
> +COMMON_FOREIGN_RPC_URL=https://red-restless-morning.bsc.quiknode.pro/<quicknode-project-id>/
We need to use the quicknode rpc, although it has limit on the eth_getlogs method, it is still faster than the commented bsc node

2021-11-08 12:03 UTC, t0mcr8se commented on alm/Dockerfile
> +RUN NOYARNPOSTINSTALL=1 yarn install --frozen-lockfile
not sure why, it was changed in this commit https://github.com/poanetwork/tokenbridge/commit/818bc4675d24b9bf1823e4979c6af4e3baf62825#diff-5fa3649758ff1fea6001a52abbc8b6f3410fbdbf30c4137a776f6431de6ebf29

2021-11-08 12:03 UTC, t0mcr8se commented on alm/Dockerfile
> +RUN NOYARNPOSTINSTALL=1 yarn install --frozen-lockfile
@leonprou do you think I should change it back to `--production` ?

2021-11-08 12:06 UTC, leonprou commented on alm/Dockerfile
> +RUN NOYARNPOSTINSTALL=1 yarn install --frozen-lockfile
mmm I actually don't care I build the files and host this on S3.
If that's what POA did, let's leave it. I though maybe you changed this for debugging purposes

2021-11-08 12:07 UTC, leonprou commented on alm/.env.example
> +COMMON_FOREIGN_RPC_URL=https://red-restless-morning.bsc.quiknode.pro/<quicknode-project-id>/
Alright.
But can you move the BSC changes to `.env.bsc.example` file. And keep `.env.example` untouched

2021-11-09 12:15 UTC, leonprou approved these changes

2021-11-09 13:04 UTC, merged